CREATE TABLE Client (
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    firstName VARCHAR(255) NOT NULL,
    lastName VARCHAR(255) NOT NULL,
    password LONGTEXT NOT NULL,
    phone VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL
);

CREATE TABLE Product (
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    price INT NOT NULL,
    image_path LONGTEXT NOT NULL
);

CREATE TABLE Administrator (
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    login VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE Cart (
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, 
    client_id INT NOT NULL,
    product_id INT NOT NULL,
    FOREIGN KEY(client_id) REFERENCES Client(id),
    FOREIGN KEY(product_id) REFERENCES Product(id)
);

CREATE TABLE Comments (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    text LONGTEXT NOT NULL
);
